//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silver.CodeAnalysis.Cs {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Silver.CodeAnalysis.Cs.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string SC0001_Description {
            get {
                return ResourceManager.GetString("SC0001_Description", resourceCulture);
            }
        }
        
        internal static string SC0001_MessageFormat {
            get {
                return ResourceManager.GetString("SC0001_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SC0001_Title {
            get {
                return ResourceManager.GetString("SC0001_Title", resourceCulture);
            }
        }
        
        internal static string SC0002_Description {
            get {
                return ResourceManager.GetString("SC0002_Description", resourceCulture);
            }
        }
        
        internal static string SC0002_MessageFormat {
            get {
                return ResourceManager.GetString("SC0002_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SC0002_Title {
            get {
                return ResourceManager.GetString("SC0002_Title", resourceCulture);
            }
        }
        
        internal static string SC0003_Description {
            get {
                return ResourceManager.GetString("SC0003_Description", resourceCulture);
            }
        }
        
        internal static string SC0003_MessageFormat {
            get {
                return ResourceManager.GetString("SC0003_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SC0003_Title {
            get {
                return ResourceManager.GetString("SC0003_Title", resourceCulture);
            }
        }
        
        internal static string SC0004_Description {
            get {
                return ResourceManager.GetString("SC0004_Description", resourceCulture);
            }
        }
        
        internal static string SC0004_MessageFormat {
            get {
                return ResourceManager.GetString("SC0004_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SC0004_Title {
            get {
                return ResourceManager.GetString("SC0004_Title", resourceCulture);
            }
        }
        
        internal static string SC0005_Description {
            get {
                return ResourceManager.GetString("SC0005_Description", resourceCulture);
            }
        }
        
        internal static string SC0005_MessageFormat {
            get {
                return ResourceManager.GetString("SC0005_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SC0005_Title {
            get {
                return ResourceManager.GetString("SC0005_Title", resourceCulture);
            }
        }
        
        internal static string SC0006_Description {
            get {
                return ResourceManager.GetString("SC0006_Description", resourceCulture);
            }
        }
        
        internal static string SC0006_MessageFormat {
            get {
                return ResourceManager.GetString("SC0006_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SC0006_Title {
            get {
                return ResourceManager.GetString("SC0006_Title", resourceCulture);
            }
        }
        
        internal static string SC0007_Description {
            get {
                return ResourceManager.GetString("SC0007_Description", resourceCulture);
            }
        }
        
        internal static string SC0007_MessageFormat {
            get {
                return ResourceManager.GetString("SC0007_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SC0007_Title {
            get {
                return ResourceManager.GetString("SC0007_Title", resourceCulture);
            }
        }
        
        internal static string SC0008_Description {
            get {
                return ResourceManager.GetString("SC0008_Description", resourceCulture);
            }
        }
        
        internal static string SC0008_MessageFormat {
            get {
                return ResourceManager.GetString("SC0008_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SC0008_Title {
            get {
                return ResourceManager.GetString("SC0008_Title", resourceCulture);
            }
        }
        
        internal static string SC0009_Description {
            get {
                return ResourceManager.GetString("SC0009_Description", resourceCulture);
            }
        }
        
        internal static string SC0009_MessageFormat {
            get {
                return ResourceManager.GetString("SC0009_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SC0009_Title {
            get {
                return ResourceManager.GetString("SC0009_Title", resourceCulture);
            }
        }
        
        internal static string SC0010_Description {
            get {
                return ResourceManager.GetString("SC0010_Description", resourceCulture);
            }
        }
        
        internal static string SC0010_MessageFormat {
            get {
                return ResourceManager.GetString("SC0010_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SC0010_Title {
            get {
                return ResourceManager.GetString("SC0010_Title", resourceCulture);
            }
        }
        
        internal static string SC0011_Description {
            get {
                return ResourceManager.GetString("SC0011_Description", resourceCulture);
            }
        }
        
        internal static string SC0011_MessageFormat {
            get {
                return ResourceManager.GetString("SC0011_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SC0011_Title {
            get {
                return ResourceManager.GetString("SC0011_Title", resourceCulture);
            }
        }
        
        internal static string SC0012_Description {
            get {
                return ResourceManager.GetString("SC0012_Description", resourceCulture);
            }
        }
        
        internal static string SC0012_MessageFormat {
            get {
                return ResourceManager.GetString("SC0012_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SC0012_Title {
            get {
                return ResourceManager.GetString("SC0012_Title", resourceCulture);
            }
        }
    }
}
